version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: e_bio_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_bio
      MYSQL_USER: e_bio_user
      MYSQL_PASSWORD: e_bio_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: e_bio_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: e_bio_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  mysql_data:
